// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAPDL_rUmjogZIWjqIw9wgxH0oW0bNmZQ',
    appId: '1:640070824460:web:4372e2c372e7ff2d56f429',
    messagingSenderId: '640070824460',
    projectId: 'lab08-cs-b3041',
    authDomain: 'lab08-cs-b3041.firebaseapp.com',
    storageBucket: 'lab08-cs-b3041.appspot.com',
    measurementId: 'G-BD6PGGX3QS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSBgVk47Nq5mz_aPFmW-sXP4TexOG9RRw',
    appId: '1:640070824460:android:a03cb2298969c8ba56f429',
    messagingSenderId: '640070824460',
    projectId: 'lab08-cs-b3041',
    storageBucket: 'lab08-cs-b3041.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHL_yicyLp-jBvFvwqRbq03CVIQs9szzk',
    appId: '1:640070824460:ios:cc21afff25e239cc56f429',
    messagingSenderId: '640070824460',
    projectId: 'lab08-cs-b3041',
    storageBucket: 'lab08-cs-b3041.appspot.com',
    iosClientId: '640070824460-5pmqqa86gg167q4okqu2ehg3ahvgvak0.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab08',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHL_yicyLp-jBvFvwqRbq03CVIQs9szzk',
    appId: '1:640070824460:ios:cc21afff25e239cc56f429',
    messagingSenderId: '640070824460',
    projectId: 'lab08-cs-b3041',
    storageBucket: 'lab08-cs-b3041.appspot.com',
    iosClientId: '640070824460-5pmqqa86gg167q4okqu2ehg3ahvgvak0.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab08',
  );
}
